# Generated by Django 5.0.6 on 2024-06-10 19:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.TextField(blank=True, null=True)),
                ('category', models.TextField()),
                ('subcategory', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
