# Generated by Django 5.0.6 on 2024-06-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profileimage_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cars',
            field=models.ManyToManyField(blank=True, null=True, to='users.car'),
        ),
    ]
