# Generated by Django 5.0.6 on 2024-06-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_car_user_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cars',
            field=models.ManyToManyField(to='users.car'),
        ),
    ]
